name: Blog Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: 1. git checkout...
        uses: actions/checkout@v1

      - name: 2. setup nodejs...
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 3. install hexo...
        run: |
          npm install hexo-cli -g
          npm install pnpm -g
          pnpm install

      - name: 4. hexo generate public files...
        run: |
          pnpm run clean
          pnpm run build
          cp ./CNAME ./public/CNAME
          cp ./README.md ./public/README.md

      - name: 5. deploy 'public files'
        run: |
          cd public
          git init
          git config user.name "w-xuefeng"
          git config user.email "xuefeng@kcalb.wang"
          git add .
          git commit -am "Feat: Github Action Auto Update Blog"
          git push --force --quiet "https://${{secrets.token}}@github.com/w-xuefeng/xiaowu-blog.git" master:master

      - name: 6. deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_ID_RSA }}
          script: cd ${{ secrets.DEPLOY_PATH }} && git pull --force



